package com.DAO;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.Model.Users;
import com.Utility.JdbcConnection;
import com.mysql.cj.protocol.Resultset;

public class UsersService implements Users_interface {
	public void createTable(){
		try(Connection con=JdbcConnection.getConnection()){
            PreparedStatement ps=con.prepareStatement("CREATE TABLE IF NOT EXISTS  users(user_id int primary key auto_increment,username varchar(50) unique not null,password varchar(50),role ENUM('ADMIN','CUSTOMER','AGENT'))");
			ps.execute();
		}catch(Exception e) {
			e.printStackTrace();
		}
	}
	@Override
	public int register(Users user)  {
		
		if(findByUsername(user.getUserName()))
		{
			System.out.println("Username already Exist try with another username");
			return 0;
		}
		int userId=0;
	    PreparedStatement ps;
	    String query="insert into users(username,password,role) values(?,?,?)";
	    try(Connection con=JdbcConnection.getConnection())
	    {
	    	ps=con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
	    	ps.setString(1, user.getUserName());
	    	System.out.println("user register "+user.getUserName());
	    	ps.setString(2, user.getPassword());
	    	ps.setString(3, user.getRole());
			int n=0;
			n=ps.executeUpdate();
		  
		    if (n > 0)
		    {
	            // Retrieve the single ID generated by THIS specific insert instead of entire table rows
	            try (ResultSet rs = ps.getGeneratedKeys()) {
	                if (rs.next()) 
	                {
	                    userId = rs.getInt(1); // Column index 1 contains the generated ID
	                }
	            }
	        } 
		    else
		    {
	            System.out.println("Something went wrong: No rows affected.");
	        }
	    }catch(Exception e) {
			e.printStackTrace();
		}
		return userId;
	}
	@Override
	public Users isExist(Users user) {
		boolean status =false;
		try(Connection con=JdbcConnection.getConnection())
		{
			String query="select * from users where username=? and password=?";
			PreparedStatement ps=con.prepareStatement(query);
			ps.setString(1, user.getUserName());
			ps.setString(2, user.getPassword());
			ResultSet rs=ps.executeQuery();
			if(rs.next()) 
			{
				Users obj=new Users(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4));
				return obj;
			}
		}catch(SQLException e) {
			e.printStackTrace();
		}
		return null;
	}
	@Override
	public List<Users> findAll(int offset,int recordsPerPage) {
		List<Users> list=new ArrayList<>();
		try(Connection con=JdbcConnection.getConnection()){
			PreparedStatement ps=con.prepareStatement("select * from users limit ?,?");
			ps.setInt(1, offset);
			ps.setInt(2, recordsPerPage);
			ResultSet rs=ps.executeQuery();
			while(rs.next())
			{
				Users obj=new Users(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4));
				list.add(obj);
			}
		}catch(SQLException e) {
			e.printStackTrace();
		}
		return list;
	}
	@Override
	public boolean findByUsername(String username) {
		String query="select * from users where username=?";
		try(Connection con=JdbcConnection.getConnection();
		    PreparedStatement ps=con.prepareStatement(query);)
		{
			ps.setString(1, username);
			ResultSet rs=ps.executeQuery();
			return rs.next();
		}catch(SQLException e) {
			e.printStackTrace();
		}
		return false;
	}
	@Override
	public int getIdByUserName(String username) {
		String query="select * from users where username=?";
		try(Connection con=JdbcConnection.getConnection();
		    PreparedStatement ps=con.prepareStatement(query);)
		{
			ps.setString(1, username);
			ResultSet rs=ps.executeQuery();
			if(rs.next())
			{
				return rs.getInt(1);
			}
		}catch(SQLException e) {
			e.printStackTrace();
		}
		return 0;
	}
	public boolean updatePasswordByUsername(String username,String password) {
		String query="update Users set password=? where username=?";
		int n=0;
		try(Connection con=JdbcConnection.getConnection();
			    PreparedStatement ps=con.prepareStatement(query);)
			{
			ps.setString(1, password);
			ps.setString(2, username);
			n=ps.executeUpdate();
			if(n>0)
			{
				return true;
			}
			}catch(SQLException e) {
				e.printStackTrace();
			}
		return false;
	}
	public int count() {
		String query="select count(*) from Users";
		int count=0;
		try(Connection con=JdbcConnection.getConnection();
				PreparedStatement ps=con.prepareStatement(query) )
		{
			ResultSet rs=ps.executeQuery();
			if(rs.next())
			{
				count=rs.getInt(1);
			}
		}catch(SQLException e) {
			e.printStackTrace();
		}
		return count;
	}
	
}
